version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: mix phx.server
    ports:
      - "4000:4000"
    volumes:
      - .:/app:cached
    env_file: .env
