FROM elixir:1.9.4

RUN mix local.hex --force && mix archive.install hex phx_new 1.4.11 --force

RUN curl -sL https://deb.nodesource.com/setup_11.x | bash - && apt-get install -y nodejs && rm -rf /var/cache/apk/*

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force
